#pragma once

#ifndef EXPERT_NODE_V2_ENABLE_CPU
#define EXPERT_NODE_V2_ENABLE_CPU 1
#endif

#ifndef EXPERT_NODE_V2_ENABLE_CPU_FP16_RESIDENT
#define EXPERT_NODE_V2_ENABLE_CPU_FP16_RESIDENT 1
#endif

#ifndef EXPERT_NODE_V2_ENABLE_CUDA
#define EXPERT_NODE_V2_ENABLE_CUDA 1
#endif

#ifndef EXPERT_NODE_V2_ENABLE_AMD
#define EXPERT_NODE_V2_ENABLE_AMD 0
#endif

#ifndef EXPERT_NODE_V2_ENABLE_INTEL
#define EXPERT_NODE_V2_ENABLE_INTEL 0
#endif

#ifndef EXPERT_NODE_V2_ENABLE_BF16
#define EXPERT_NODE_V2_ENABLE_BF16 1
#endif

#if (EXPERT_NODE_V2_ENABLE_CUDA == 1) && (EXPERT_NODE_V2_ENABLE_BF16 == 1)
#define EXPERT_NODE_V2_ENABLE_CUDA_BF16 1
#else
#define EXPERT_NODE_V2_ENABLE_CUDA_BF16 0
#endif
