#pragma once

#ifndef EXPERT_NODE_V2_ENABLE_CUDA
#define EXPERT_NODE_V2_ENABLE_CUDA 1
#endif

#ifndef EXPERT_NODE_V2_ENABLE_ONEAPI
#define EXPERT_NODE_V2_ENABLE_ONEAPI 0
#endif

#ifndef EXPERT_NODE_V2_ENABLE_BF16
#define EXPERT_NODE_V2_ENABLE_BF16 1
#endif

#if (EXPERT_NODE_V2_ENABLE_CUDA == 1)
#define EXPERT_NODE_V2_HAS_CUDA 1
#else
#define EXPERT_NODE_V2_HAS_CUDA 0
#endif

#if (EXPERT_NODE_V2_HAS_CUDA == 1) && (EXPERT_NODE_V2_ENABLE_BF16 == 1)
#define EXPERT_NODE_V2_HAS_CUDA_BF16 1
#else
#define EXPERT_NODE_V2_HAS_CUDA_BF16 0
#endif

#if defined(SYCL_LANGUAGE_VERSION) && (EXPERT_NODE_V2_ENABLE_ONEAPI == 1)
#define EXPERT_NODE_V2_HAS_ONEAPI 1
#else
#define EXPERT_NODE_V2_HAS_ONEAPI 0
#endif
